version: '3'
services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: sqlserver
        environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=Password123
        ports:
        - 1433:1433
        volumes:
        - ./data:/var/opt/mssql/data
        restart: on-failure