version: '3'
services:
  redis:
    container_name: timemail-redis
    image: redis:latest
    volumes:
      - ./data:/data
      - ./redis.conf:/etc/redis.conf
    ports:
      - 6379:6379
    command: redis-server /etc/redis.conf --appendonly yes
    restart: on-failure